apiVersion: apps/v1
kind: Deployment
metadata: 
   name: webserver 
   labels:
      app: webserver
spec:
   replicas: 1
   selector:
      matchLabels:
        app: webserver
   template:
      metadata:
          name: webserver
          labels:
            app: webserver
      spec:
        containers:
           - name: server
             image: myimage2:latest
             port:
               - containerPort: 80

---
apiVersion: v1
kind: Service 
metadata: 
   name: nodeport
spec:
  type: Nodeport
  selector: 
     app: webserver
  ports:
     - port: 80
       targetPort: 80
       nodePort: 30007 
