apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: webserver 
    version: v1
    tier: frontend
spec: 
  containers:
     - name: server1
       image: nginx
       ports:
         - containerPort: 80
     - name: server2
       image: nickchase/rss-php-nginx:v1
       ports:
         - containerPort: 88

