apiVersion: v1
kind: Pod
metadata:
   name: project
   labels:
     app: project
spec:
  containers:
     - name: exam-project
       image: steveric/exam-project
       ports:
         - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
   name: project-service
spec:
  type: NodePort
  selector:
    app: project
  ports:
     - port: 80
       targetPort: 80 
       nodePort: 30009
